name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -  
      name: Create env file
      run: |
        touch .env
        echo "DEBUG=False" >> .env
        echo "HOST=0.0.0.0" >> .env
        echo "PORT=5000" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
    -
      name: Build the Docker image
      run: |
        docker build --file Dockerfile -t redirector:latest .
        docker save -o ./redirector.tar redirector
    -
      name: Delete env file
      run: |
        rm -rf .env
    -
      name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_KEY }}
        known_hosts: 'known-hosts'
    -
      name: Adding to known hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    -
      name: Transfer file onto server
      run: rsync -avz ./redirector.tar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/redirector/
    -
      name: Deploy on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd redirector
          sudo docker stop $(sudo docker ps -q --filter ancestor=redirector)
          sudo docker rm $(sudo docker ps -a -q --filter ancestor=redirector)
          sudo docker rmi redirector
          sudo docker load -i redirector.tar
          sudo rm -rf redirector.tar
          sudo docker run -d -p 5000:5000 redirector